baseURL: "https://blogdotales.netlify.app/"
title: Tales Gomes
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Tales Gomes
    description: "Meu site pessoal"
    keywords: [Blog, Portfolio, PaperMod]
    author: Tales Gomes
    # author: ["Me", "You"] # multiple authors
    images: ["dark-blue-avatar.png"]
    DateFormat: "January 2, 2006"
    defaultTheme: dark # dark, light, auto
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "pacman.ico"
        #favicon16x16: "<link / abs url>"
        #favicon32x32: "<link / abs url>"
        #apple_touch_icon: "<link / abs url>"
        #safari_pinned_tab: "<link / abs url>"

    label:
        text: "Página inicial"
        #icon: /apple-touch-icon.png
        #iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Tales Gomes
        subtitle: "Engenheiro da Computação e Analista de dados"
        imageUrl: "dark-blue-avatar.png"
        imageWidth: 120
        imageHeight: 120
        imageTitle: Pacman Ghost
        buttons:
            - name: Blog
              url: post
            - name: Assuntos
              url: /categories/
            - name: Tags
              url: tags
            
    # home-info mode
    homeInfoParams:
        Title: "Olá \U0001F44B"
        Content: Sejam bem vindos a minha página pessoal!

    socialIcons:
        - name: linkedin
          # url: "https://www.linkedin.com/in/talesgomes27/"
        - name: github
          url: "https://github.com/talesgomes27"
        - name: email
          url: "mailto:talesgomes27@gmail.com"
        - name: curriculo
          url: "https://talesgomes27.github.io/curriculo/"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
    #    hidden: true # hide everywhere but not in structured data
    #    hiddenInList: true # hide on list pages and home
    #    hiddenInSingle: true # hide on single page

    #editPost:
    #    URL: "https://github.com/<path_to_repo>/content"
    #    Text: "Suggest Changes" # edit text
    #    appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: Blog
          name: Blog
          url: /post/
          weight: 10
        - identifier: Assuntos
          name: Assuntos
          url: /categories/
          weight: 20
        - identifier: Tags
          name: Tags
          url: /tags/
          weight: 30
        - identifier: Pesquisa
          name: Pesquisa
          url: search/
          weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
